version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:3.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake db:create db:migrate
      - run: bundle exec rspec
